"""Packs the generator output (valid/ + broken/ + valid.json + broken.json) into the kit: kit/images/decode/{valid,broken}/*,
kit/data/images-valid.js, kit/data/images-broken.js and kit/manifest/images.tsv.
x86 reference checksums (this build's values for the lossy files) come from x86ref.json beside this script, if present.
Run (after gen_valid.py and gen_broken.py):  python pack.py
  IMG_OUT  the generator output folder (default: out/ beside this script; use the same value as for the generators)
  IMG_KIT  the kit folder to pack into (default: ../../kit, the real kit; point it at a scratch copy to try a change)
Only kit/images/decode/ is ever cleaned. The manifest lists every file of the images page: the page, its lib file, its data files and
its test files; the page and the lib file are hand-written, so their rows are hashed from the kit as it is when pack.py runs
(run pack.py again after editing images.html or lib/images-lib.js).
"""
import os, re, json, base64, hashlib, shutil, sys
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.environ.get('IMG_OUT') or os.path.join(HERE, 'out')
KIT = os.environ.get('IMG_KIT') or os.path.normpath(os.path.join(HERE, '..', '..', 'kit'))
valid = json.load(open(os.path.join(OUT, 'valid.json')))
broken = json.load(open(os.path.join(OUT, 'broken.json')))
x86 = json.load(open(os.path.join(HERE, 'x86ref.json'))) if os.path.exists(os.path.join(HERE, 'x86ref.json')) else {}
for d in ('images/decode/valid', 'images/decode/broken'):
    shutil.rmtree(os.path.join(KIT, d), ignore_errors=True)       # only this page's own test-file folder is ever cleaned
for d in ('images/decode/valid', 'images/decode/broken', 'data', 'manifest'):
    os.makedirs(os.path.join(KIT, d), exist_ok=True)
manifest = []
TOOLS = 'kit-tools/images/'
def cite(s):
    """the generators are named by their place in the record: gen_valid.py -> kit-tools/images/gen_valid.py"""
    return re.sub(r'(?<![/\w])(gen_valid|gen_broken|vp8l|imgtools|jpegseg)\.py', lambda m: TOOLS + m.group(1) + '.py', s)
def b64of(kind, rec):
    src = os.path.join(OUT, kind, rec['id'] + '.' + rec['fmt'])
    data = open(src, 'rb').read()
    dst = os.path.join(KIT, rec['file'])
    shutil.copyfile(src, dst)
    assert hashlib.sha256(data).hexdigest() == rec['sha256']
    manifest.append((rec['file'], rec['sha256'], cite(rec['source'] + ('; ' + rec['why'] if rec.get('why') else ''))))
    return base64.b64encode(data).decode()

def js(obj): return json.dumps(obj, separators=(',', ':'))
vout = []
for v in valid:
    o = dict(id=v['id'], fmt=v['fmt'], type=v['type'], w=v['w'], h=v['h'], exact=v['exact'], exactOp=v.get('exactOp'), ref=v['ref'], x86=x86.get(v['id']) if v['ref'] else None, semi=v.get('semi'), why=v['why'], b64=b64of('valid', v))
    vout.append(o)
bout = []
for b in broken:
    o = dict(id=b['id'], fmt=b['fmt'], type=b['type'], base=b['base'], allowed=b['allowed'], phase=b['phase'], why=b['why'], reaches=b['reaches'], b64=b64of('broken', b))
    bout.append(o)
hdr = ('// Venetium test kit, images page: test files as base64 (file:// pages are opaque origins: no fetch() of local files, so the data '
       'travels in .js files).\n// GENERATED by kit-tools/images/ (gen_valid.py, gen_broken.py, pack.py); sources and hashes: manifest/images.tsv.\n')
open(os.path.join(KIT, 'data/images-valid.js'), 'w', newline='\n').write(
    hdr + '// Valid files. exact = FNV-1a of the RGBA bytes computed from the generator\'s own pixels (independent of any decoder); ref = 8x8 grid of the mean colour (composited on white) of the SOURCE image the lossy file was encoded from, tol = allowed difference per channel;\n// x86 = the checksum the x86 build of this record produced for the lossy file: a REGRESSION reference for the ARM32 run, NOT an independent expectation (the independent check for these files is ref/tol).\n// semi = number of pixels with 0 < alpha < 255 in the picture the file is made from (host-counted by gen_valid.py; only set for the files that have an x86 reference; kit-tools/images/alpha_survey.py checks it). The canvas read-back un-premultiplies such pixels and x86 and ARMv7 NEON round ties differently, so for semi > 0 the full-RGBA x86 checksum is shown as info, not judged.\nwindow.IMG_VALID = [\n' + ',\n'.join(js(o) for o in vout) + '\n];\n')
open(os.path.join(KIT, 'data/images-broken.js'), 'w', newline='\n').write(
    hdr + '// Broken files. base = the valid sibling (control); allowed = the outcome classes the page accepts for this file ("corrupt" is accepted for none); phase and reaches = the decoder path the file is BUILT to drive, argued from the code (the page does not prove at run time that a file took that path).\nwindow.IMG_BROKEN = [\n' + ',\n'.join(js(o) for o in bout) + '\n];\n')
for f, src in (('data/images-valid.js', 'generated by kit-tools/images/pack.py from the generator output of kit-tools/images/gen_valid.py and kit-tools/images/x86ref.json: the valid files listed above (base64)'),
               ('data/images-broken.js', 'generated by kit-tools/images/pack.py from the generator output of kit-tools/images/gen_broken.py: the broken files listed above (base64)'),
               ('images.html', 'hand-written for this kit: the images page (decoder map argued from the Chromium tree, see its info rows)'),
               ('lib/images-lib.js', 'hand-written for this kit: helpers of the images page (blob: URL -> <img> -> canvas read-back, createImageBitmap, checksums, outcome classifier)')):
    manifest.append((f, hashlib.sha256(open(os.path.join(KIT, f), 'rb').read()).hexdigest(), src))
manifest.sort()
open(os.path.join(KIT, 'manifest/images.tsv'), 'w', newline='\n').write(
    'path\tsha256\tsource\n' + '\n'.join('\t'.join((a, b, c.replace('\t', ' ').replace('\n', ' '))) for a, b, c in manifest) + '\n')
print('packed', len(vout), 'valid,', len(bout), 'broken; data js sizes:', [os.path.getsize(os.path.join(KIT, f)) for f in ('data/images-valid.js', 'data/images-broken.js')], '; manifest rows:', len(manifest))
