# Writes venetium/tests/kit/manifest/wasm.tsv: every file the wasm page owns, with its sha256 as it is on disk NOW, and where it comes from.
#   python manifest.py           write the manifest (run it LAST, after the final edit of any file below and after gen_wasm_data.py)
#   python manifest.py --check   exit 1 if the manifest differs from what would be written now (stale hash, missing file, changed provenance)
# Columns: path (relative to the kit folder), sha256, source. Paths never leave the kit; the tools (this folder) are not shipped and have no rows.
import sys, os, hashlib, subprocess
sys.dont_write_bytecode = True
HERE = os.path.dirname(os.path.abspath(__file__))
KIT = os.path.normpath(HERE + '/../../kit')
REPO = os.path.normpath(HERE + '/../../../..')
NODE = os.environ.get('KIT_NODE', 'F:/cr/src/third_party/node/win/node.exe')
J = REPO + '/s10/jit/'
TOOL = 'venetium/tests/kit-tools/wasm/gen_wasm_data.py'

def sha(path):
    with open(path, 'rb') as f: return hashlib.sha256(f.read()).hexdigest()
nodev = subprocess.check_output([NODE, '-p', 'process.version + " (V8 " + process.versions.v8 + ", " + process.arch + ")"']).decode().strip()

ROWS = [
    ('wasm.html', 'hand-written (the page; BATCH-X86-2 section 1, BATCH-DEVICE-1 section 1 and its follow-up: wasm tier asserted against configs.js, i64 shift digests, memory script, executed phases / step counts / operator groups asserted against the generator record)'),
    ('lib/wasm-asm.js', "hand-written: the body of s10Bytes() is lines 3-13 of s10/jit/wasm.js (sha256 %s) unchanged except for the wrapper; withNonce() is original" % sha(J + 'wasm.js')),
    ('lib/wasm-cases.js', 'hand-written: the two cases of s10/jit/wasm.js verbatim + the ext digest / probe / memory-script runners + memShape / opsShape (executed phases, step counts, functions, groups against the generator record); also run in Node by kit-tools/wasm/node_check.js'),
    ('lib/wasm-tier.js', 'hand-written: the V8 natives (%IsTurboFanFunction, %IsLiftoffFunction, %WasmTierUpFunction, ...); a SyntaxError without --allow-natives-syntax, so wasm.html loads it only when the configuration has natives'),
    ('data/wasm-data.js', 'generated by %s (python reference semantics, exact integers) and cross-checked by venetium/tests/kit-tools/wasm/node_check.js on Node %s: base64 of the two modules below + the host answers: s10/jit/expected.py (sha256 %s) = expected.txt (%s) = node-x64.txt (%s) for wasm_i32 / wasm_i64; ext digests, spin, memloop and the memory script from the python model, plus the record of the memory-script phases / step counts and of the operator groups (ext.mem.expect, ext.expect) that the page checks what it executed against' % (TOOL, nodev, sha(J + 'expected.py'), sha(J + 'expected.txt'), sha(J + 'node-x64.txt'))),
    ('media/wasm-s10.wasm', 'the module that s10/jit/wasm.js (sha256 %s) assembles byte by byte, dumped by running that script unchanged in Node %s; written by %s; NOT loaded by the page - the same bytes are inline (base64) in data/wasm-data.js' % (sha(J + 'wasm.js'), nodev, TOOL)),
    ('media/wasm-ext.wasm', 'own work: assembled by %s (i32/i64 operator functions incl. i64 variable and constant-amount shifts, ld/st/grow/size and the narrow / extending / unaligned / float / offset / constant-address memory functions on one exported memory, spin, memloop); NOT loaded by the page - the same bytes are inline (base64) in data/wasm-data.js' % TOOL),
]
text = 'path\tsha256\tsource\n' + ''.join('%s\t%s\t%s\n' % (p, sha(KIT + '/' + p), src) for p, src in ROWS)
out = KIT + '/manifest/wasm.tsv'
if '--check' in sys.argv:
    have = open(out, encoding='utf-8', newline='').read() if os.path.exists(out) else None
    print('manifest/wasm.tsv: ' + ('OK (%d files)' % len(ROWS) if have == text else 'STALE or missing - run manifest.py'))
    sys.exit(0 if have == text else 1)
os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, 'w', encoding='utf-8', newline='\n') as w: w.write(text)
print('wrote', out, len(ROWS), 'rows')
